language: node_js
node_js:
  - '12.8.2'

before_script:
  - yarn
  - yarn global add codecov

script:
  - yarn build
  - yarn lint:fix
  - yarn test

after_success:
  - codecov

notifications:
  email:
    on_success: never
